repos:
  -   repo: https://github.com/Yelp/detect-secrets.git
      rev: v1.4.0
      hooks:
      -   id: detect-secrets
          args: ['--baseline', '.secrets.baseline']
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
      -   id: no-commit-to-branch
          args: [--branch, develop, --branch, master, --pattern, release/.*]
